image: docker:20.10.12
services:
- docker:dind
stages:
- deploy_to_production
variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
deploy_to_production:
  image: alpine
  stage: deploy_to_production
  before_script:
    - apk update
    - apk add --no-cache openssh
    - echo "$SSH_PRIVATE_KEY" >> key.pem
    - chmod 400 key.pem
  variables:
    SSH_P: "ubuntu@195.49.215.151"
    URL_P: "respublica"
    PATH_P: "/home/ubuntu/http/www"
  script:
    - ssh -i key.pem -o 'StrictHostKeyChecking no' $SSH_P git -C $PATH_P/$URL_P checkout -- .
    - ssh -i key.pem -o 'StrictHostKeyChecking no' $SSH_P git -C $PATH_P/$URL_P pull origin main
    - ssh -i key.pem -o 'StrictHostKeyChecking no' $SSH_P "docker restart node"
    - sleep 10
    - ssh -i key.pem -o 'StrictHostKeyChecking no' $SSH_P "docker exec node json-server --watch /var/www/respublica/server/db.json --host 0.0.0.0 --port 3000"
    - ssh -i key.pem -o 'StrictHostKeyChecking no' $SSH_P "docker restart nginx"
  when: manual
  after_script:
    - rm key.pem
  only:
    - main